### ISSUE TITLE
Turntable acceleration and deceleration problem

### ISSUE THREAD

**Issue by Melkiyby** [kadirilkimen/babyBear-3D-printer#1]
Hi! I am using your project. But I got a small bug. When the motion trajectory passes through the center of the turntable and it needs to turn 180 degrees, the rotation starts with a smooth acceleration, but when it reaches 180 degrees, the table stops without slowing down and the motor can jump a few steps. 
Could you help find a solution to this problem?
https://youtube.com/shorts/HvbnYGIs35s?feature=share
And one more bug related to the z-axis. After some time, it stops rising for crossings and works only down.
It's definitely not a mechanical problem. On the firmware from Rob Mink [(URL)](https://github.com/RobMink/UpdatedPolarFirmware---Marlin) it worked more stable, but also not perfect. On a complex engraving with many ups and downs, the result is about the same.

![20230201_151129](https://user-images.githubusercontent.com/17052717/216040597-cef3b046-cbb0-4b88-a82e-51ae4f94bffe.jpg)
![20230201_151253](https://user-images.githubusercontent.com/17052717/216040603-30e87aee-491c-4382-8ee5-e3bee66a0a15.jpg)

**Comment by kadirilkimen** [comment]
In January, I developed polar kinematics for Marlin and the Marlin team merged it into the firmware. 
If you use this old cartesian system firmware, I strongly suggest to move on to the Marlin with polar kinematics.
Old cartesian system custom firmware had some acceleration issues. May be this new polar kinematics in Marlin would fix your issue.

If you already using the marlin firmware with polar kinematics, Then I am not exactly sure what it would be. I tested it for almost  hundred prints and I don't see acceleration problem.
May be the DEFAULT_SEGMENTS_PER_SECOND  in the configuration.h would create such problem. You can try reducing it.

POLAR_FAST_RADIUS in the configuration.h designed to overcome 3D printing extrusion problems and weird feedrates on the center of the polar axis. If you have any movement inside this radius circle, it uses maximum speed that your configuration allows. You can try to reduce it and see if it helps. These all very related to your hardware setup.  So I don't think I can replicate the problem without your exact hardware.


About this video:
https://youtube.com/shorts/HvbnYGIs35s?feature=share

I believe the result should be a straight line. If so, You have a significant offset on the tool. Which means, your tooltip is not aligned to the center of the polar axis. Therefore there is an offset and there is an unreachable radius on the center. 

You have two options : 
1 - Move the tooltip to exact center of the polar axis mechanically.
2 - Measure the offset and enter it as POLAR_CENTER_OFFSET on the configuration.h file in the Marlin. This option will leave an unreachable circle and crop everything in this circle.


For the Z axis problem;
Polar axis calculations has nothing to do with Z axis. I don't think it would be related to the polar kinematics. I have two different machine with different boards. I didn't observe any problem with Z.

I would suggest you to make sure;
-  There is no torque problem on your Z setup. It can cause only down direction. If the motor just have enough torque to move the Z axis up, it can reduce by time because of heat ( both on the driver or the motor ).
- Z acceleration is low enough to handle the Z axis weight.
- There is no electrical noise on end stops etc.

Rob's firmware uses scara kinematics to achieve polar movements. If any of the firmware won't completely fix the Z problem, It feels like it is more likely a torque or acceleration thing.

If you can share more details ( pictures may be ) about your hardware, it would help me to understand.

**Comment by Melkiyby** [comment]
Thanks for the quick response.  The first request is to take a video of how the rotation of the table behaves in your case.  X Axis and Y Axis are programmatically set to zero and send the x axis to -1mm. The second request from X and Y=0 is to move to X=9 and after X=-10.  Will there be a difference in the movement of the rotary axis in your case? In the first case, my rotary axis does not rotate and the motor vibrates loudly at a high frequency.  I calibrated the rotation speed on the firmware with Cartesian coordinates and the axis rotated perfectly.  A little clarification, I don't use homing at the moment.  Maybe it affects the firmware.
At the moment I'm using the latest (yesterday's) 2.1.x bugfix and the edited config from your post.  Hardware BTT Skr pro and tmc2209 with uart.  In my config, backlash compensation is activated for two linear axes.  S-curve and adaptive step smoothing are disabled.  I tried to activate linear advance - the result is the same.

**Comment by kadirilkimen** [comment]
If your machine is not a babyBear, it is probably better to move this conversation to the Marlin firmware repository.

I will perform some tests when I have time of course. And actually made very similar tests in different dimensions. In my case, I didnt notice skipping steps.

I have this video right now: https://youtube.com/shorts/hO4HH4sqpeg?feature=share

It periodicly draws lines passing from zero and cause 180degree rotation. As you can see, there is no any shift on the print. There are more aggressive prints, I am going to upload a video about the babyBear.


Anyway, Since polar coordinates are not offsetting friendly like cartesians, setting zero point for X axis programmatically is a bad idea.

I strongly suggest to install an end switch to locate zero point of X axis on the exact center of the rotary axis.

Your machine's design is also important. What is the reduction ratio of the polar axis?

If you have a small reduction like 3:1 and if you perform a very small movement near center with a slow feedrate,  it may be the reason of the vibration.

Please, if your machine is not a babyBear, open an issue for marlin firmware and I will continue there. If the machine is a babyBear, lets keep the conversation here.



Please provide the following details:

- Share the structure of your machine.

- Share the both configuration file. So we can see if something off.

**Comment by Melkiyby** [comment]
Hi. I have posted my issue in the marlin repository [https://github.com/MarlinFirmware/Marlin/issues/25330](url)

**Comment by kadirilkimen** [comment]
Anyone experiences this problem, please follow the issue opened in Marlin repository : https://github.com/MarlinFirmware/Marlin/issues/25330
